In [2]:
# import requests
import pandas as pd
# import sys
# import os
# import numpy as np
import tensorflow as tf
# import random
# import cv2
# import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os
import PIL
import PIL.Image
import glob

# from keras.models import Sequential
# # -- Import from keras_preprocessing not from keras.preprocessing -- # #
# from keras_preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
# from keras.layers import Dense, Activation, Flatten, Dropout, BatchNormalization
# from keras.layers import Conv2D, MaxPooling2D
# from keras import regularizers, optimizers

# from sklearn.metrics import ConfusionMatrixDisplay
# from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, BatchNormalization, Conv2D, Dense, Dropout, Flatten, MaxPooling2D,GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

# import tensorflow_datasets as tfds

In [12]:
data_dir = './rotations/'
img_height = 200
img_width = 200
batch_size = 1


<TensorSliceDataset shapes: (), types: tf.string>

In [28]:
for x in glob.glob(os.path.join(data_dir, '*')):
    print(x[-6:-5])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
1
1
1
1
0
0
0
0
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0


In [39]:

df = pd.DataFrame(data={'images': [x for x in glob.glob(os.path.join(data_dir, '*'))],
                        'labels': [x[-6:-5] for x in glob.glob(os.path.join(data_dir, '*'))]
                       })

dataset = tf.data.Dataset.from_tensor_slices((list(df['images'].values), df['labels'].values)).batch(2)

for x, y in dataset.take(10):
  print(x.shape, y)
# (2, 64, 64, 3) tf.Tensor([b'ok' b'not ok'], shape=(2,), dtype=string)

(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)
(2,) tf.Tensor([b'0' b'0'], shape=(2,), dtype=string)


In [46]:
print(dataset.take(1))


<TakeDataset shapes: ((None,), (None,)), types: (tf.string, tf.string)>
